# Generated by Django 2.1.1 on 2018-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Chef', 'Chef'), ('Membre', 'Membre')], max_length=100),
        ),
    ]
