# Generated by Django 2.1.1 on 2018-10-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180929_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompensationAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=13)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Budget')),
            ],
            options={
                'ordering': ('budget', 'category'),
            },
        ),
        migrations.CreateModel(
            name='CompensationAccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=3)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.CompensationAccountCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastedAccountingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('U', 'Unique'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annually')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastedaccountingentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='forecastedaccountingentry',
            name='compensation_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.CompensationAccount'),
        ),
        migrations.AddField(
            model_name='compensationaccount',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.CompensationAccountCategory'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='compensation_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.CompensationAccount'),
        ),
    ]
