# Generated by Django 2.1.1 on 2018-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20181008_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationaccountcategory',
            name='type',
            field=models.CharField(choices=[('Rentrées', 'Rentrées'), ('Dépenses', 'Dépenses')], max_length=200),
        ),
        migrations.AlterField(
            model_name='forecastedaccountingentry',
            name='type',
            field=models.CharField(choices=[('Unique', 'Unique'), ('Hebdomadaire', 'Hebdomadaire'), ('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Annuel', 'Annuel')], max_length=1),
        ),
    ]
