# Generated by Django 2.1.1 on 2018-10-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20181011_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationaccountcategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.CompensationAccountCategory'),
        ),
    ]
