# Generated by Django 2.1.1 on 2018-10-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20181013_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAccountingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Annuel', 'Annuel')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('compensation_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.CompensationAccount')),
                ('counterparty_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_accounting_entry_counterparty', to='accounting.Account')),
            ],
        ),
        migrations.RenameField(
            model_name='forecastedaccountingentry',
            old_name='next_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='forecastedaccountingentry',
            name='type',
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='counterparty_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entry_counterparty', to='accounting.Account'),
        ),
        migrations.AddField(
            model_name='forecastedaccountingentry',
            name='counterparty_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasted_accounting_entry_counterparty', to='accounting.Account'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='compensation_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.CompensationAccount'),
        ),
        migrations.AlterField(
            model_name='forecastedaccountingentry',
            name='compensation_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.CompensationAccount'),
        ),
        migrations.AddField(
            model_name='forecastedaccountingentry',
            name='recurring_accounting_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.RecurringAccountingEntry'),
        ),
    ]
